### ISSUE TITLE
Calculating population statistics

### ISSUE THREAD

**Issue by acordiner** [grantjenks/python-runstats#16]
runstats only seems to allow the calculation of the _sample_ variance/stdev. Is it possible to also calculate the _population_ variance/stdev? i.e. using a denominator of N rather than N-1

If the functionality doesn't exist, I'm happy to submit a pull request for this. numpy provides a `ddof` parameter for `std()`/`var()` to achieve this; I think something similar could be easily implemented in runstats.

**Comment by grantjenks** [comment]
Sounds reasonable. Pull request welcome.

**Comment by acordiner** [comment]
Created pull request #17

**Comment by grantjenks** [comment]
Released to PyPI at version 1.6.3
