### ISSUE TITLE
Initialize from Numpy array

### ISSUE THREAD

**Issue by rammy22** [grantjenks/python-runstats#21]
Would you consider adding a constructor to Statistics that initialises the list of observation with a Numpy array in Cython instead of iterating over the argument list and pushing elements one by one?
I'm attempting to use this compute stats on array of billion of observations and initialisation is killing the performance.
Thanks for the great work!

**Comment by grantjenks** [comment]
I'm open to those changes but I'm not sure how to write that code. I think you would want to specialize init for the numpy scenario. We could certainly make the max and min calculation faster then. But how do you calculate the other values like rho, etc.

Overall, sounds useful, pull request welcome.

**Comment by grantjenks** [comment]
Here's an idea: write an "extend" method that calculates a Statistics obeject for the given iterable and then uses "iadd" to combine. Assuming numpy has methods for mean, max, skew, etc., I think you could derive the internal constants from those.

**Comment by rammy22** [comment]
I would replace https://github.com/grantjenks/python-runstats/blob/master/runstats/fast.pyx#L38 with 
```python
self.list = np_arr.tolist()
```

**Comment by grantjenks** [comment]
"Push" is not a method on a list, it's a method on Statistics objects. The method updates several internal variables. Statistics objects do not record a list of values "pushed" to them.
