### ISSUE TITLE
Provide Native Binaries in Wheels

### ISSUE THREAD

**Issue by grantjenks** [grantjenks/python-runstats#23]
Consider using: 
https://github.com/joerick/cibuildwheel/blob/master/README.md

**Comment by FlorianWilhelm** [comment]
Hi @grantjenks, I would also totally favour having binary wheels since the sdist distribution often fails when GCC is too old or some dev library is missing.

**Comment by FlorianWilhelm** [comment]
It's actually easy, just run 'python setup.py bdist_wheel' and use twine to upload them to PyPI.

**Comment by grantjenks** [comment]
I don't think it's quite so easy. The trick is running "bdist_wheel" for all the different binary platforms that are to be supported, gathering those files together and then uploading all of them to PyPI. There's a combination of variables: Python version, OS, and chipset. Take a look at [numpy](https://pypi.org/project/numpy/#files) and you'll see they upload 21 different binaries for Mac/Linux/Windows support on Python 2.7, 3.5, 3.6, 3.7 and x86_64 / i686 chipsets.

**Comment by FlorianWilhelm** [comment]
With some small shell script and conda that should be still possible at least for Linux which is the major platform that's gonna cover 90% of your users at least.

**Comment by grantjenks** [comment]
Pull request welcome.

**Comment by FlorianWilhelm** [comment]
😉

**Comment by grantjenks** [comment]
This will be done in the next version major of runstats. (Hopefully in the next month or so. The "release" GitHub Action should do all the heavy lifting required.)

**Comment by FlorianWilhelm** [comment]
Cool! Check out [publish-package.yml  of PyScaffold](https://github.com/pyscaffold/pyscaffold/blob/master/.github/workflows/publish-package.yml) if you need an example. It runs automatically for every tag on master, uses git information (setuptools-scm via PyScaffold) to set the correct version for the package, and uses tox to generate a clean build.

**Comment by grantjenks** [comment]
Merged in #35 (created a new release.yml GitHub Action)
