### ISSUE TITLE
Build error when using Python 3.7 + Cython

### ISSUE THREAD

**Issue by jbergbrede** [grantjenks/python-runstats#24]
Hi, I am experiencing issues when trying to build runstats 1.7.1 under python 3.7 using cython.
Next to some warnings about using parentheses (which are also present in python 3.6), I get the following error:
```
runstats/fast.c: In function ‘__Pyx_PyCFunction_FastCall’:
runstats/fast.c:10294:5: error: too many arguments to function ‘(struct PyObject * (*)(struct PyObject *, struct PyObject * const*, Py_ssize_t))meth’
     return (*((__Pyx_PyCFunctionFast)meth)) (self, args, nargs, NULL);
     ^
```
Thank you for your work!
Best, Jannis

**Comment by grantjenks** [comment]
Try again. I just released an update with Python 3.7 support (I think).
