### ISSUE TITLE
Unable to open 'fast.pyx' in vscode

### ISSUE THREAD

**Issue by sytelus** [grantjenks/python-runstats#25]
When runstats throws an error (for example, trying to get stddev with only 1 item), IDEs like Visual Studio Code looks for .pyx file and as it is not found (because installed from pip, even with cython), the IDE throws error:

```
Unable to open 'fast.pyx'
```

This is unfortunate because it hides original error message.

**Suggested fix**
  1. Generate pyx or remove its dependency if installed from pip. 
  2. Return nan instead of divide by 0 error for stddev and variance.

**Comment by grantjenks** [comment]
fast.pyx will be removed in the next version of runstats.
