### ISSUE TITLE
Docs: count and push

### ISSUE THREAD

**Issue by sytelus** [grantjenks/python-runstats#26]
I think below two should be answered in documentation:

1. I'm very confused by `push` method. Does this mean `runstats` keep all the data in memory (I hope not!). Why is there no `pop`? If runstate didn't keep all data in memory, its interface should not be container like.
2. How to get count? Turns out use `len`. This is good python standard but took me a while to figure out because I assumed runstats isn't a container. It would be great to have `count()` method instead.

**Comment by grantjenks** [comment]
1. "push" is not a container-like method.
2. No. Use len()

The tutorial has details: http://www.grantjenks.com/docs/runstats/#tutorial
