### ISSUE TITLE
Statistics.stddev crashing with division by 0 error if only one value

### ISSUE THREAD

**Issue by crazyhouse33** [grantjenks/python-runstats#27]
Runstat version '1.8.0'
Python: 3.7
Using runstat with cython. 

Also it would be cool to provide a way (maybe its allready there, but not in your doc) on how to use basic python for debugging purpose. Here you have a pdb session showing the bug:
```

-> stdevs= self.stat.stddev() if self.want_stdev else []
(Pdb) n
ZeroDivisionError: float division by zero
> /opt/handCraftedUtilityShit/eprof2/eprof/event.py(17)to_kvhf()
-> stdevs= self.stat.stddev() if self.want_stdev else []   
(Pdb) p self.stat.get_state()
(1.0, 74689.0, 0.0, 0.0, 0.0, 74689.0, 74689.0)
```

**Comment by baldoalessandro** [comment]
This happens also without cython but I think is the intended behavior and what you can expect from a stdev implementation

**Comment by grantjenks** [comment]
The exception is by design. If you want to LBYL then you can check the len or with EAFP you can catch the exception.
