### ISSUE TITLE
Does this package support "batch" operations?

### ISSUE THREAD

**Issue by Linux-cpp-lisp** [grantjenks/python-runstats#32]
Hi all,

I'm working on a problem where I need to compute running statistics on scalars that come in "batches." The naive implementation is something like:
```python
s = Statistics()
for batch in batches:
    for scalar in batch:
        s.push(scalar)
```
where `batch` is a PyTorch `Tensor` or a numpy `ndarray`. Obviously, the performance of this is not good. Does this library support some kind of `.update()` in the optimized Cython implementation that efficiently goes through the `memoryview` and does the update calculations?
```python
s = Statistics()
for batch in batches:
    s.update(batch)
```

Thanks!

**Comment by grantjenks** [comment]
Nope. There's no fast-path for arrays that support `memoryview`.

One thing you could do those is parallelize the computation. You could compute the statistics of each "batch" and then combine statistics objects.

**Comment by Linux-cpp-lisp** [comment]
That path would still involve calling `s.push(...)` for every individual element of the batch (ndarray), right?

**Comment by grantjenks** [comment]
Yup. Although you could call `Statistics(iterable=array)` and it'll iterate it using Cython.

**Comment by Linux-cpp-lisp** [comment]
OK — thanks for the quick answer!
