### ISSUE TITLE
New release for newer Python versions

### ISSUE THREAD

**Issue by BorisWiegand** [grantjenks/python-runstats#34]
Hi,

under Python 3.9 I get the following compile error on pip install "runstats==1.8.0":
`runstats/fast.c(9837): error C2039: "tp_print" ist kein Member von "_typeobject".`

Under Python 3.8, the installation works. Seems as if in Python 3.9 support of tp_print was removed. It would be very nice if you could make a new release that works under newer Python versions. The current release is from 2019. 

Thank you very much in advance. 

Kind regards

Boris Wiegand

**Comment by grantjenks** [comment]
Release of new version is blocked on #35

**Comment by grantjenks** [comment]
Released in v2.0.0 on PyPI
