### ISSUE TITLE
Improve Cython Support

### ISSUE THREAD

**Issue by grantjenks** [grantjenks/python-runstats#5]
Add documentation regarding Cython support and speedup.

There's an interesting permutation of install scenarios. I released the package from my macbook using "sdist bdist_wheel --universal" so that included the binary I built locally and source. On [PyPI](https://pypi.python.org/pypi/runstats/) you'll see the Mac OSX binary alongside the source. So when you install, there are several options:

* You run "pip install runstats" on a similar Mac and get my binary.
* You run "pip install runstats" on Windows or Linux and only get the pure-Python version.
* You run "pip install --no-binary runstats runstats" on any system and it'll try to build the package with Cython and if that fails then fallback to the pure-Python version.

I added `tests/benchmark.py` to observe the Cython-impact. I also added types. Example benchmark output:

```
$ python benchmark.py 
core.Statistics: 0.0214369297028
fast.Statistics: 0.000623941421509
  Stats Speedup: 33.36x faster
core.Regression: 0.0528829097748
fast.Regression: 0.00235199928284
   Regr Speedup: 21.48x faster
```

So `Statistics` objects are 30x faster and Regression objects are 20x faster.

See #2 also.

**Comment by grantjenks** [comment]
It might be better to just include the "sdist" version for now. AppVeyor will build Windows binaries but it looks complicated and doesn't include other binaries.

I wonder how numpy has such broad support: https://pypi.python.org/pypi/numpy

**Comment by FlorianWilhelm** [comment]
Could you with the help of Travis add support for Linux 64bit bdist_wheel files on PyPI?

**Comment by grantjenks** [comment]
Is installing from a binary wheel a hard requirement? I was thinking of just uploading the source distribution "sdist" and telling users that if Cython is installed then it will be used. That would let you skip the "--no-binary runstats" option.

I read through the [Travis deployment to PyPI docs](https://docs.travis-ci.com/user/deployment/pypi/) and it says they support "bdist_wheel" distributions but I wonder, is that Linux 64bit? The [Python packaging docs](https://packaging.python.org/distributing/#platform-wheels) says Linux binary wheels aren't yet supported.

In the end, I'm just not sure the best way to deploy binary distributions. A good writeup/docs would go a long way if you could find it.

**Comment by FlorianWilhelm** [comment]
Well, providing only one sdist might be a viable solution here since it is pragmatic and won't cause you much work in the future. Otherwise the number of combinations of 32/64bit, win/linux/macos, py2/py3 and many others explodes and will cause you much pain. 
Regarding Windows and PyPI I just checked that at least Numpy provides wheels for Linux: https://pypi.python.org/pypi/numpy/1.11.2

**Comment by grantjenks** [comment]
Exactly, the combinations for binary support is prohibitive for such a small package. I wish someone would provide free support for open source projects. I know that AppVeyor does so for Windows binaries but they do not include Mac and Linux binaries. For corporate users it's not much an issue because presumably they've standardized deployments and run DevPI and are used to building their own binaries. But for small projects it's tough.

I guess the setuptools docs are out of date given the binary numpy for Linux support. You may ask the numpy folks how they do it.

If I just published the "sdist" version then I wonder what happens if you do:

    pip install Cython runstats

Does that give runstats `setup.py` access to Cython? Probably not. So you'd have to do:

    pip install Cython
    pip install runstats

The other option is to remove the Cython dependency and just ship the generated `fast.c` file directly. That's probably best when combined with the `sdist` option.

**Comment by FlorianWilhelm** [comment]
I also think that the second version is the right one. Besides Cython you still need GCC available for it to work. Python packaging really is a mess. I also use Conda a lot for exactly that reason.

**Comment by grantjenks** [comment]
I don't think it's too bad actually. `bdist_wheel` is useful but no one wants to contribute build machines for open source projects. Given the cost, that's not too surprising. But as a scenario, I'm glad Python supports it.

I think the best way to go forward is to use "sdist" with "fast.c" checked into the repo. That removes the Cython requirement from "setup.py". So when you type "pip install runstats" and you have a C compiler then you'll get the Cython code. And if you type "pip install runstats" and you lack a C compiler then you'll fall back to the Python code.

Business users should be using [DevPI](http://doc.devpi.net/latest/) and they can clone, build "bdist_wheel", and upload the binary to their local mirror and avoid needing a C compiler in deployments.

**Comment by FlorianWilhelm** [comment]
Sounds like a good solution.

**Comment by grantjenks** [comment]
I tried to make this work and deployed something at 1.3.0. The Cython-generated file fast.c was in the repo and setup.py no longer depended on Cython. I then uploaded a source distribution to PyPI. But it didn't work as expected. If the build failed then the install failed. It didn't fall back to the pure-Python version as I had hoped it would.

So I added the Cython requirement back (at 1.4.0) and stuck with the source distribution. So now if you "pip install runstats" and you have Cython installed then you get the binary extension and otherwise you get the pure-Python solution.

This is "good-enough" for me. I think something better could be done if you studied the simplejson setup.py file where they do a better job of falling-back. If you want to work on that, I'll leave this issue open. Otherwise, in a week or two, I'll close it.

**Comment by FlorianWilhelm** [comment]
I am happy with that solution.  I guess if you have a C compiler installed it is no problem to also install cython right? And since I use mostly Linux which is kind of unthinkable without GCC I guess we can close this issue. Thanks again for the fast cython implementation, that helps a lot.

**Comment by grantjenks** [comment]
Updated docs regarding cython support and deployed v1.5.0
